version: '3.8'
networks:
  mutant_net:
    external: true
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mutant_api
    networks:
      - mutant_net
    ports:
      - "3333:3333"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=desafio_mutant
    networks:
      - mutant_net
